spring.application.name=keycloak-ldap-demo
server.address=0.0.0.0
server.port=8010
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/keycloak-ldap
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT secret key (keep this long and random in production)
jwt.secret=MySuperSecretKeyThatIsLongEnoughForHS256Algorithm1234567890
jwt.expiration=86400000
#ldap
spring.ldap.urls=ldap://localhost:10389
spring.ldap.base=dc=example,dc=com
spring.ldap.username=uid=admin,ou=system
spring.ldap.password=secret
ldap.user.search-base=ou=people
ldap.user.search-filter=(uid={0})
ldap.group.search-base=ou=groups
ldap.group.search-filter=(member={0})
ldap.group.role-attribute=cn

#keycloak
# ??? Keycloak / OAuth2 Resource Server ??????????????????
# This URL is where Spring fetches Keycloak's public keys
# and validates incoming JWTs automatically
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/keycloak-ldap

# ??? Keycloak client credentials (for token endpoint calls)
keycloak.server-url=http://localhost:9090
keycloak.realm=keycloak-ldap
keycloak.client-id=spring-boot-keycloak-ldap-app
keycloak.client-secret=Euth0gAUtWk1NUlkFpm0dHqb31qzKnNV
